var portfolio = [
{url: "https://www.safechain.io/", class: "state_OH funds2 business_B2B industry_finance  " ,img: "SafeChain"},
{url: "https://www.bizzycoffee.com/", class: "state_MN funds2 business_B2C industry_food industry_other " ,img: "BizzyCoffee"},
{url: "https://hippomanager.com/", class: "state_KY funds2 business_B2B  industry_enterprise " ,img: "HippoManager"},
{url: "https://changedynamix.io/", class: "state_MI funds2 business_B2B industry_enterprise  " ,img: "ChangeDynamix"},
{url: "http://www.virtualkey.co/", class: "state_IL funds2 business_B2B business_B2C industry_realestate industry_analytics " ,img: "VirtualKey"},
{url: "https://www.parrable.com/", class: "state_MI funds2 business_B2B industry_analytics industry_marketing " ,img: "Parrable"},
{url: "https://www.amopportunities.org/", class: "state_IL funds2 business_B2C industry_healthcare industry_education " ,img: "AMOpportunities"},
{url: "http://backstitch.io/", class: "state_MO funds2 business_B2B industry_enterprise  " ,img: "BackStitch"},
{url: "http://www.idelictech.com/", class: "state_PA funds2 business_B2B industry_transportation  " ,img: "IdelicTech"},
{url: "https://cfxtrading.com/", class: "state_IL funds2 business_B2B business_B2C industry_finance  " ,img: "CFXMarkets"},
{url: "http://www.employstream.com/", class: "state_OH funds2 business_B2B industry_enterprise  " ,img: "EmployStream"},
{url: "https://ryvit.com/", class: "state_MO funds2 business_B2B industry_enterprise  " ,img: "Ryvit"},
{url: "https://www.geneticure.com/", class: "state_MN funds2 business_B2B industry_healthcare  " ,img: "Geneticure"},
{url: "http://www.markitmedical.com/", class: "state_IL funds2 business_B2B business_B2C industry_healthcare  " ,img: "MarkItMedical"},
{url: "https://www.datacubes.com/", class: "state_IL funds2 business_B2B industry_finance  " ,img: "DataCubes"},
{url: "https://www.kin.us/", class: "state_IL funds2 business_B2C industry_finance  " ,img: "Kin"},
{url: "http://rapchat.me/", class: "state_OH funds2 business_B2C industry_entertainment industry_apps " ,img: "RapChat"},
{url: "https://cheddargetter.com/", class: "state_IN funds2 business_B2B industry_finance  " ,img: "CheddarGetter"},
{url: "http://opendorse.com/", class: "state_NE funds2 business_B2B industry_entertainment industry_marketing " ,img: "Opendorse"},
{url: "http://www.completeset.com/", class: "state_KY funds2 business_B2C industry_entertainment industry_apps " ,img: "CompleteSet"},
{url: "http://www.rentalutions.com/", class: "state_IL funds2 business_B2B business_B2C industry_realestate  " ,img: "Rentalutions"},
{url: "http://www.scriptdrop.co/", class: "state_OH funds2 business_B2B industry_healthcare  " ,img: "ScriptDrop"},
{url: "https://andcostello.com/", class: "state_IN funds2 business_B2B  industry_enterprise " ,img: "Costello"},
{url: "https://www.astronomer.io/", class: "state_OH funds2 business_B2B industry_analytics industry_enterprise " ,img: "Astronomer"},
{url: "http://familytech.com/", class: "state_OH funds2 business_B2C industry_apps  " ,img: "FamilyTech"},
{url: "http://www.petronics.io/", class: "state_IL funds2 business_B2C  industry_analytics " ,img: "Petronics"},
{url: "https://www.chowlyinc.com/", class: "state_IL funds2 business_B2B industry_food  " ,img: "Chowly"},
{url: "https://anglr.com/", class: "state_PA funds2 business_B2C industry_entertainment industry_apps " ,img: "ANGLR"},
{url: "https://cladwell.com/", class: "state_OH funds2 business_B2C industry_ecommerce industry_apps " ,img: "Cladwell"},
{url: "http://www.branchmessenger.com/", class: "state_MN funds2 business_B2B business_B2C industry_enterprise  " ,img: "BranchMessenger"},
{url: "http://www.knowledgehound.com/", class: "state_IL funds2 business_B2B industry_analytics  industry_enterprise" ,img: "KnowledgeHound"},
{url: "https://www.rewards21.com/", class: "state_IL funds2 business_B2B business_B2C industry_ecommerce industry_marketing " ,img: "Rewards21"},
{url: "http://www.printwithme.com/", class: "state_IL funds2 business_B2C industry_other  " ,img: "PrintWithMe"},
{url: "http://spatial.ai/", class: "state_OH funds2 business_B2B industry_realestate industry_transportation industry_analytics" ,img: "Spatial"},
{url: "https://realync.com/", class: "state_IN funds2 business_B2B industry_realestate  " ,img: "Realync"},
{url: "https://www.pactsafe.com/", class: "state_IN funds1 business_B2B industry_education  industry_enterprise" ,img: "PactSafe"},
{url: "http://explorersurgical.com/", class: "state_IL funds2 business_B2B industry_healthcare  " ,img: "ExplORerSurgical"},
{url: "http://www.ballotready.org/", class: "state_IL funds1 business_B2B business_B2C industry_education industry_analytics " ,img: "BallotReady"},
{url: "https://sportsmantracker.com/", class: "state_MI funds2 business_B2C industry_entertainment industry_apps " ,img: "SportsmanTracker"},
{url: "https://www.dattus.com/", class: "state_IN funds1 business_B2B industry_analytics  " ,img: "Dattus"},
{url: "http://www.lunalights.org/", class: "state_IL funds1 business_B2B industry_healthcare industry_analytics " ,img: "LunaLights"},
{url: "http://conceptdrop.com/", class: "state_IL funds1 business_B2B business_B2C industry_marketing  industry_enterprise" ,img: "ConceptDrop"},
{url: "http://jetpackworkflow.com/", class: "state_PA funds1 business_B2B   industry_enterprise" ,img: "JetPackWorkflow"},
{url: "https://www.page-vault.com/", class: "state_IL funds1 business_B2B industry_education  industry_enterprise" ,img: "PageVault"},
{url: "http://www.blocksixanalytics.com/", class: "state_IL funds1 business_B2B industry_entertainment industry_analytics " ,img: "BlockSixAnalytics"},
{url: "https://regrouptherapy.com/", class: "state_IL funds1 business_B2B industry_healthcare  " ,img: "RegroupTherapy"},
{url: "http://www.boxfox.co/", class: "state_IN funds1 business_B2B industry_ecommerce industry_marketing " ,img: "BoxFox"},
{url: "http://eastmanegg.com/", class: "state_IL funds1 business_B2C industry_food industry_other " ,img: "EastmanEgg"},
{url: "http://www.scanalyticsinc.com/", class: "state_WI funds1 business_B2B industry_analytics  " ,img: "Scanalytics"},
{url: "http://www.dabble.co/", class: "state_IL funds1 business_B2C industry_marketing  " ,img: "Dabble"},
{url: "http://www.wearehearken.com/", class: "state_IL funds1 business_B2B industry_entertainment  " ,img: "Hearken"},
{url: "http://pairade.com/", class: "state_IL funds1 business_B2C industry_entertainment industry_apps " ,img: "Pairade"},
{url: "http://www.zipfitdenim.com/", class: "state_IL funds1 business_B2C industry_ecommerce  " ,img: "ZipFit"},
{url: "http://www.sentictechnologies.com/", class: "state_IL funds1 business_B2B industry_marketing  " ,img: "Sentic"},
{url: "http://www.skyepack.com/", class: "state_IN funds1 business_B2C industry_education  " ,img: "Skyepack"},
{url: "https://www.glidera.io/", class: "state_IL funds1 business_B2C industry_finance  " ,img: "Glidera"},
{url: "https://mimirhq.com/", class: "state_IN funds1 business_B2B business_B2C industry_education  " ,img: "Mimir"},
{url: "https://www.app-press.com/", class: "state_IN funds1 business_B2B industry_enterprise  " ,img: "AppPress"}
];


